### ISSUE TITLE
Invalid Synthax error in library

### ISSUE THREAD

**Issue by rmib200** [eitcom/pyEIT#65]
Hi, I've been trying to learn to use my SpectraEIT. I've installed the pyeit lib and was looking at the examples but I run into this invalid synthax error constantly.
![image](https://user-images.githubusercontent.com/19299616/188489958-1a431574-18b0-46d8-aec9-7b0b67fc20e8.png)
Other similar erros I've found are in `from pyeit.eit.interp2d import sim2pts` with: 
```
  File "/usr/local/lib/python3.7/dist-packages/pyeit/eit/base.py", line 13, in <module>
    from pyeit.eit.protocol import PyEITProtocol

  File "<fstring>", line 1
    (ex_mat=)
```
The version I am using is pyeit = 1.2.2

Is there a way to fix it? Or other version I should use? I really want to use this for my project with the SpectraEIT.

**Comment by liubenyuan** [comment]
What's the your python version and package environment? If you are using spectra, you may use the version it specified in their GUI.

**Comment by ChabaneAmaury** [comment]
Have you tried running it on a local computer with a proper anaconda env ? It could be related to Google Colab itself for some reasons.

Also, could you provide an access to (or at least part of) the notebook so we can recreate this issue?

**Comment by cancelliere** [comment]
There is no minimum Python version specified in the `environment.yml` file , but the cause of the issue is due to a feature that has been introduced in Python 3.8, namely the f-string syntax with a trailing `=` sign.
Look for `bpo-36817` [here](https://docs.python.org/3/whatsnew/changelog.html#id244).
I had Python 3.7 installed and had to update to make it work.

Hope it helps!
